# Lutz Examples

## Loops

In [1]:
while True:
    reply = input('Enter Number:')
    if reply == 'stop':
        break
    elif not reply.isdigit():
        print('Bad!' * 8)
    else:
        print(int(reply) ** 2)
print('bye')

Enter Number:5
25
Enter Number:k
Bad!Bad!Bad!Bad!Bad!Bad!Bad!Bad!
Enter Number:stop
bye


In [15]:
while True:
    reply = input('Enter text:')
    if reply == 'stop': break
    try:
        num = int(reply)
    except:
        print('Bad!' * 8)
    else:
        print(num ** 2)
print('Bye')

Enter text:Helo
Bad!Bad!Bad!Bad!Bad!Bad!Bad!Bad!
Enter text:2
4
Enter text:stop
Bye


In [17]:
while True:
    reply = input('Enter text:')
    if reply == 'stop': break
    try:
        print(float(reply) ** 2)
    except:
        print('Bad!' * 8)
print('Bye')

Enter text:45
2025.0
Enter text:5.5
30.25
Enter text:sto
Bad!Bad!Bad!Bad!Bad!Bad!Bad!Bad!
Enter text:stop
Bye


##Lists

In [18]:
M=[[1,2,3],[4,5,6],[7,8,9]]

In [43]:
[row[:2] for row in M]

[[1, 2], [4, 5], [7, 8]]

In [35]:
2 ** 16
2 / 5, 2 / 5.0

"spam" + "eggs"
S = "ham";S
"eggs " + S
S * 5
S[:0]
"green %s and %s" % ("eggs", S)
'green {0} and {1}'.format('eggs', S)

('x',)[0]
('x', 'y')[1]

L = [1,2,3] + [4,5,6]; L
L, L[:], L[:0], L[-2], L[-2:]
([1,2,3] + [4,5,6])[2:4]
[L[2], L[3]]
L.reverse(); L
L.sort(); L
L.index(4)

{'a':1, 'b':2}['b']
D = {'x':1, 'y':2, 'z':3}; D
D['w'] = 0; D
D['x'] + D['w']
D[(1,2,3)] = 4; D
list(D.keys()), list(D.values()), (1,2,3) in D

[[]], ["",[],(),{},None]

([[]], ['', [], (), {}, None])

In [64]:
L=range(4); L
L[-1000:100]
L[1:0]=['?']; L

[0, '?', 1, 2, 3]

In [69]:
L=range(4); L
L[2]=[]; L
L=range(4)
L[2:3]=[];L

[0, 1, 3]

## If/Patterns

In [3]:
x = 10
while x:
    x = x-1 # Or, x -= 1
    if x % 2 != 0: continue # Odd? -- skip print
    print(x, end=' ')

8 6 4 2 0 

In [22]:
y=3
x = y // 2 # For some y > 1
while x > 1:
    if y % x == 0: # Remainder
        print(y, 'has factor', x)
        break # Skip else
    x -= 1
else: # Normal exit
    print(y, 'is prime')

3 is prime


## Functions

In [4]:
def min1(*args):
    res = args[0]
    for arg in args[1:]:
        if arg < res:
            res = arg
    return res

def min2(first, *rest):
    for arg in rest:
        if arg < first:
            first = arg
    return first

def min3(*args):
    tmp = list(args) # Or, in Python 2.4+: return sorted(args)[0]
    tmp.sort()
    return tmp[0]

def min4(*args):
    return sorted(args)[0]

print(min1(3, 4, 1, 2))
print(min2(3, 4, 1, 2))
print(min3(3, 4, 1, 2))
print(min2("bb", "aa"))
print(min3([2,2], [1,1], [3,3]))
print(min4(3,4,5,6))

1
1
1
aa
[1, 1]
3


In [7]:
def minmax(test, *args):
    res = args[0]
    for arg in args[1:]:
        if test(arg, res):
            res = arg
    return res

def lessthan(x, y): return x < y # See also: lambda, eval
def grtrthan(x, y): return x > y

print(minmax(lessthan, 4, 2, 1, 5, 6, 3)) # Self-test code
print(minmax(grtrthan, 4, 2, 1, 5, 6, 3))

1
6


In [8]:
def func(a, *pargs):
    print(a, pargs)

func(1, 2, 3)

1 (2, 3)


In [9]:
def func(a, **kargs):
    print(a, kargs)
    
func(a=1, c=3, b=2)

1 {'c': 3, 'b': 2}


In [10]:
def func(a, b, c=3, d=4): print(a, b, c, d)
    
func(1, *(5, 6))

1 5 6 4


# NumPy Examples

In [7]:
import numpy as np

In [17]:
def numpysum(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c

def pythonsum(n):
    a = list(range(n))
    b = list(range(n))
    c = []

    for i in list(range(len(a))):
        a[i] = i ** 2
        b[i] = i ** 3
        c.append(a[i] + b[i])

    return c

In [9]:
numpysum(5)

array([ 0,  2, 12, 36, 80])

In [23]:
pythonsum(5)

[0, 2, 12, 36, 80]

In [29]:
a=np.arange(5)
a.dtype
a.shape

(5,)

In [33]:
m = np.array([np.arange(2), np.arange(2)])
m.shape

(2, 2)

In [38]:
a = np.array([[1,2],[3,4]])
a[1,1]

4

In [41]:
a = np.arange(9)
a[3:7]
a[:7:2]
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [82]:
b = np.arange(24)
b=b.reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [83]:
b[0,0,0]
b[:,0,0]
b[0]
b[0,1]
b[0,1,::2]
b[:,:,1]
b[:,1]
b[0,:,1]
b[0,::-1,-1]
b[::-1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [84]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [85]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [86]:
b.shape=(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [87]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [88]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [101]:
b2=b
b2.resize(2,12)
b2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [99]:
b.resize(2,12)

In [108]:
b=b2
b.resize(6,4)
print(b.ndim)
b.T

2


array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [109]:
b.ndim

2

In [111]:
import numpy as np

i2 = np.eye(2)
print(i2)
np.savetxt("eye.txt", i2)

[[ 1.  0.]
 [ 0.  1.]]


## Classes

In [9]:
class Person:
    def __init__(self, name, job=None, pay=0):
        self.name = name
        self.job = job
        self.pay = pay
    def lastName(self): # Behavior methods
        return self.name.split()[-1] # self is implied subject
    def giveRaise(self, percent):
        self.pay = int(self.pay * (1 + percent)) # Must change here only
    def __repr__(self): # Added method
        return '[Person: %s, %s]' % (self.name, self.pay)
    
class Manager(Person):
    def __init__(self, name, pay): # Redefine constructor
        Person.__init__(self, name, 'mgr', pay)
    def giveRaise(self, percent, bonus=.10): # Redefine at this level
        Person.giveRaise(self, percent + bonus) # Call Person's version

class Department:
    def __init__(self, *args):
        self.members = list(args)
    def addMember(self, person):
        self.members.append(person)
    def giveRaises(self, percent):
        for person in self.members:
            person.giveRaise(percent)
    def showAll(self):
        for person in self.members:
            print(person)

if __name__ == '__main__':
    bob = Person('Bob Smith')
    sue = Person('Sue Jones', job='dev', pay=100000)
    tom = Manager('Tom Jones', 50000)
    development = Department(bob, sue) # Embed objects in a composite
    development.addMember(tom)
    development.giveRaises(.10) # Runs embedded objects' giveRaise
    development.showAll() # Runs embedded objects' __repr__

[Person: Bob Smith, 0]
[Person: Sue Jones, 110000]
[Person: Tom Jones, 60000]
